# kubectl create -f k8-api-deployment.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api
  labels:
    app: ms-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ms-api
  template:
    metadata:
      labels:
        app: ms-api
        service: ms-api
    spec:
      containers:
        - name: ms-api
          image: vermavarun/api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
---
apiVersion: v1
kind: Service
metadata:
  name: ms-api
  labels:
    app: ms-api
    service: webapi
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    service: ms-api