apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ui
  labels:
    app: ms-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ms-ui
  template:
    metadata:
      labels:
        app: ms-ui
        service: ms-ui
    spec:
      containers:
        - name: ms-ui
          image: vermavarun/ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ms-ui
  labels:
    app: ms-ui
    service: ms-ui
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    service: ms-ui